font_family        JetBrains Mono
bold_font          auto
italic_font        auto
bold_italic_font   auto
font_size          12

# CURSOR HIDE
mouse_hide_wait -5.0

# WINDOW SETTINGS
window_padding_width 4

# CURSOR
cursor_trail 500
cusor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# Background
background_opacity 0.90
window_margin_width 8
window_padding_width 8
dynamic_background_opacity yes

# SOUND
enable_audio_bell no

# BEGIN_KITTY_THEME
# Ayu
include current-theme.conf
# END_KITTY_THEME
